#' accordion_input_helpers
#'
#' Create a series of secondary functions that generate child elements of the
#' accordion and process arguments. These functions are added to a nested list
#' object that is called in the main function.
#'
#' @noRd
accordion_input_helpers <- list()


#' set_html_ids
#'
#' Define a function that generates the IDs and data attributes for properly
#' linking elements across helper functions
#'
#' @param inputId a user defined ID
#'
#' @noRd
accordion_input_helpers$set_html_ids <- function(inputId) {
    list(
        group = inputId,
        checkbox_id = paste0(inputId, "-accordionInput"),
        button_id = paste0(inputId, "-accordionBtn"),
        content_id = paste0(inputId, "-accordionSection"),
        label_id = paste0(inputId, "-accordionInputLabel")
    )
}

#' @name heading
#'
#' Define a function that returns the checkbox input element and the accordion
#' toggle button, which is used to open and close the hidden section. This
#' function is used in the primary function along with `content()`.
#'
#' @param ids a list object generated by set_html_ids
#' @param title user defined title
#' @param checked a logical argument to determin if the input element
#'      should be checked by default
#'
#' @importFrom htmltools tags tagList
#' @noRd
accordion_input_helpers$heading <- function(ids, title, checked) {
    # <input>
    i <- tags$input(
        type = "checkbox",
        class = "accordion__checkbox",
        id = ids$checkbox_id
    )

    # add checked attribute (if applicable)
    if (checked) i$attribs$checked <- "true"

    # generate markup
    tagList(
        i,
        # <label>
        tags$label(
            id = ids$label_id,
            `for` = ids$checkbox_id,
            class = "accordion__heading",
            title
        ),
        # <button>
        tags$button(
            id = ids$button_id,
            class = "accordion__toggle",
            `aria-controls` = ids$content_id,
            `aria-labelledby` = ids$label_id,
            `aria-expanded` = "false",
            rheroicons::rheroicon(
                name = "chevron_down",
                type = "outline",
                classnames = "toggle__icon"
            )
        )
    )
}

#' content
#'
#' Define a function that creates the collapsible element in the accordion.
#' This function is used in the primary function along with the `heading()`
#' function.
#'
#' @param ids a list object generated by set_html_ids
#' @param content user defined html element or tagList of elements
#'
#' @importFrom htmltools tags tagList
#' @noRd
accordion_input_helpers$content <- function(ids, content) {
    tags$section(
        id = ids$content_id,
        class = "accordion__content",
        `aria-labelledby` = ids$label_id,
        hidden = "",
        content
    )
}