
#' accordion_helpers
#' Create a series of secondary functions that generate child elements of the
#' accordion and process arguments. These functions are added to a nested list
#' object that is called inthe main function.
#' @noRd
accordion_helpers <- list()


#' set_html_ids
#' Define a function that generates the IDs and data attributes for properly
#' linking elements across helper functions
#' @param inputId a user defined ID
#' @noRd
accordion_helpers$set_html_ids <- function(inputId) {
    ns <- NS(namespace = inputId)
    ids <- list(
        group = inputId,
        heading_id = ns("accordionHeading"),
        button_id = ns("accordionBtn"),
        content_id = ns("accordionSection")
    )
    return(ids)
}

#' @name heading
#' Define a function that returns the heading of the accordion section. This
#' function returns a heading element (<h4>) that places the title in a button.
#' The button is used to open and close the hidden section. This function is
#' used in the primary function along with the `content()` function.
#' @param ids a list object generated by set_html_ids
#' @param title user defined title
#' @param props the processed arguments generated from the validate_props func
#' @importFrom rheroicons outline
#' @noRd
accordion_helpers$heading <- function(ids, title, heading_level) {

    # <h*>
    h <- tags[[heading_level]](
        id = ids$heading_id,
        class = "accordion-heading",
        `data-accordion-group` = ids$group
    )

    # <button>
    b <- tags$button(
        id = ids$button_id,
        class = "accordion-button",
        `data-accordion-group` = ids$group,
        `aria-controls` = ids$content_id,
        `aria-expanded` = "false",
        tags$span(
            class = "accordion-button-label",
            title
        ),
        outline$chevron_down(
            aria_hidden = TRUE,
            class = "accordion-button-icon"
        )
    )

    # append button to heading
    h$children <- b

    # return
    return(h)

}

#' \code{content}
#' Define a function that creates the collapsible element in the accordion.
#' This function is used in the primary function along with the `heading()`
#' function.
#' @param ids a list object generated by set_html_ids
#' @param html user defined html element or tagList of elements
#' @noRd
accordion_helpers$content <- function(ids, html) {
    s <- tags$section(
        id = ids$content_id,
        class = "accordion-section",
        `data-accordion-group` = ids$group,
        `aria-labelledby` = ids$heading_id,
        hidden = "",
        html
    )
    return(s)
}